[build]
command = """
if [ ! -f "$HOME/.cargo/env" ]; then
  curl https://sh.rustup.rs -sSf | sh -s -- -y
fi \
 && . "$HOME/.cargo/env" \
 && rustup target add wasm32-unknown-unknown \
 && (command -v trunk >/dev/null 2>&1 || cargo install trunk) \
 && trunk build --release
"""
publish = "dist"
