name: preprod

on:
  push:
    branches:
      - preprod
  pull_request:
    branches:
      - preprod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust target and tools
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install trunk wasm-bindgen-cli

      - name: Build WASM front
        run: trunk build --release
